# Control file for Travis CI (http://travis-ci.org)
# Must be located in the root directory of the Git repository.

# No Emails
notifications:
  email: false

sudo: required

# Disabling the distro, so we get the latest:
# dist:
#   - trusty

# We define the job matrix explicitly, in order to be able to minimize the
# combinations of runtime environments.
# For OS-X, using an explicit matrix is required anyway, because Travis at
# this point only has half-baked support for Python on OS-X that does
# not work. Also, on OS-X, it needs to be invoked with language=generic
# and an empty 'python' variable in order to prevent that Travis attempts
# to install Python.
matrix:
  include:
    - os: linux
      language: python
      python: "2.7"
    - os: linux
      language: python
      python: "3.4"
#    - os: linux
#      language: python
#      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
#    - os: linux
#      language: python
#      python: "pypy-5.3.1"  # Python 2.7.10
#    - os: osx
#      language: generic
#      python:
#      env:
#        - PYTHON=2
#    - os: osx
#      language: generic
#      python:
#      env:
#        - PYTHON=3

before_install:
  - if [[ "$TRAVIS_BRANCH" == "manual-ci-run" ]]; then
      export _NEED_REBASE=true;
    fi
  - if [[ -n $_NEED_REBASE ]]; then git fetch origin master; fi
  - if [[ -n $_NEED_REBASE ]]; then git branch master FETCH_HEAD; fi
  - if [[ -n $_NEED_REBASE ]]; then git rebase master; fi
  - git branch -av

# commands to install dependencies
# added pip install --upgrade coverage below to correct problem in
# issue 21 where python-coveralls installs old version of coverage
install:
  - if [[ "$TRAVIS_BRANCH" == "manual-ci-run" || "$TRAVIS_PULL_REQUEST_BRANCH" == "manual-ci-run" ]]; then
      export _MANUAL_CI_RUN=true;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "${PYTHON:0:1}" == "2" ]]; then
        export PYTHON_CMD=python;
        export PIP_CMD=pip;
      else
        export PYTHON_CMD=python3;
        export PIP_CMD=pip3;
      fi;
    else
      export PYTHON_CMD=python;
      export PIP_CMD=pip;
    fi;
    echo "PYTHON_CMD=$PYTHON_CMD";
    echo "PIP_CMD=$PIP_CMD"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "${PYTHON:0:1}" == "2" ]]; then
        OSX_PYTHON_PKG=python;
      else
        OSX_PYTHON_PKG=python3;
      fi;
      echo "OSX_PYTHON_PKG=$OSX_PYTHON_PKG";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew search python && brew ls --versions $OSX_PYTHON_PKG && brew upgrade $OSX_PYTHON_PKG || brew install $OSX_PYTHON_PKG;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      virtualenv venv -p $PYTHON_CMD && source venv/bin/activate;
    fi
  - env |sort
  - pip list
  - pip install --upgrade pip
  - pip list
  - make install
  - make develop
  - pip install python-coveralls
  - pip install --upgrade coverage
  - pip list

# commands to run builds & tests
script:
  - if [[ -n $_MANUAL_CI_RUN ]]; then make build; fi
  - if [[ -n $_MANUAL_CI_RUN ]]; then make builddoc; fi
  - make check
  - make test

after_success:
  - if [[ -z $_MANUAL_CI_RUN && $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi
